project:
  type: website
  output-dir: docs

website:
  title: "Educational Enterprise Pvt. Ltd."
  site-url: https://educationalenterprise.com.np
  google-analytics: "G-M0W0K6HDJX"
  image: "/assets/media/images/logo/Educational-Enterprise-Logo.png"
  favicon: "/assets/media/images/logo/Educational-Enterprise-Logo_small.png"
  twitter-card: true
  navbar:
    title: false
    logo: "/assets/media/images/logo/Educational-Enterprise-Logo.png"
    logo-alt: "Educational Enterprise Pvt. Ltd. Logo"
    foreground: "#3F88C5"
    background: "#FFF9EC"
    pinned: true
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: contactus.qmd
        text: Contact Us
  page-footer:
    foreground: "#FFF9EC"    
    background: "#3F88C5"
    left:
      - text: Copyright Â© 1961-<script>document.write( new Date().getFullYear() );</script>&nbsp;<br><a href="https://www.educationalenterprise.com.np" target="_top">Educational Enterprise Pvt. Ltd.</a> All rights reserved. <br>Designed by <a href="https://www.mohitshrestha.com.np" target="_top">Mohit Shrestha</a>.
    right:
      - icon: envelope-at
        href: "mailto:contact@educationalenterprise.com.np?Subject=Hello%20from%20Educational%20Enterprise%20Pvt.%20Ltd.%20Website"
      - icon: facebook
        href: https://www.facebook.com/EducationalEnterprise/   
      - icon: instagram
        href: https://www.instagram.com/EducationalEnterprise/
      - icon: twitter-x
        href: https://x.com/EduEntBooks/
      - icon: linkedin
        href: https://www.linkedin.com/company/EducationalEnterprise/
    border: true

format:
  html:
    page-layout: full
    theme:
      light:
        - lux # a predefined bootswatch theme
        - brand # theming derived from `_brand.yml`
      dark:
        - lux # a predefined bootswatch theme
        - brand # theming derived from `_brand.yml`
    css: /assets/css/styles.css # a user-defined customization
    toc: true

brand:
  light: /brand/_brand_eduent_light.yml
  dark: /brand/_brand_eduent_dark.yml
